name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2
    
    - name: Setting up docker username and password
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}

      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASS

    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/healthcaredeploy .
    
    - name: Pushing the image to docker hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/healthcaredeploy

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        uses: shimataro/ssh-key-action@v2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        with:
          key: $PRIVATE_KEY
          known_hosts: ubuntu@ec2-18-232-38-208.compute-1.amazonaws.com
            
        run: |
        
          sudo docker pull rjritik/healthcaredeploy &&
          sudo docker run -dp 80:8000 rjritik/healthcaredeploy && exit
